// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  const runtimeEnv = typeof process !== 'undefined' ? process.env : undefined;
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || runtimeEnv?.SUPABASE_URL || 'https://kytfgpljksqlrannvcil.supabase.co';
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || runtimeEnv?.SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInJlZiI6Imt5dGZncGxqa3NxbHJhbm52Y2lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg5MDgxNTMsImV4cCI6MjA5NDQ4NDE1M30.gCRzR05NBERc3XJxnXdtKDasSAYFoP1RJgrKiYcJ9Bg';

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

